import { deriveDemoEventPhase, type DemoAuditStep, type DemoEvent } from "../../../shared/demo-events";

export type ArtifactViewerMetadata = { label: string; value: string };

export type ArtifactViewerFocusNode = {
  ref: string;
  title: string;
  subtitle?: string | null;
  resourceType?: string | null;
  siteName?: string | null;
  siteJurisdiction?: string | null;
  noteText?: string | null;
  content: unknown;
  copyText?: string;
  metadata?: ArtifactViewerMetadata[];
};

export type ArtifactViewerGroup = {
  id: string;
  label: string;
  refs: string[];
};

export type ArtifactViewerSinglePayload = {
  kind?: "single";
  title: string;
  subtitle?: string;
  content: unknown;
  copyText?: string;
  metadata?: ArtifactViewerMetadata[];
  noteText?: string | null;
};

export type ArtifactViewerJwtPayload = {
  kind: "jwt";
  title: string;
  subtitle?: string;
  jwt: string;
  copyText?: string;
  metadata?: ArtifactViewerMetadata[];
  noteText?: string | null;
};

export type ArtifactViewerContextPayload = {
  kind: "context";
  title: string;
  subtitle?: string;
  summary?: string | null;
  focusRef: string;
  nodes: ArtifactViewerFocusNode[];
  groups: ArtifactViewerGroup[];
};

export type ArtifactViewerEventPayload = {
  kind: "event";
  title: string;
  subtitle?: string;
  event: DemoEvent;
};

export type ArtifactViewerEventSummary = {
  description: string;
  fields: ArtifactViewerMetadata[];
  steps?: DemoAuditStep[];
  patientMatch?: string | null;
  noteText: string;
};

export type ArtifactViewerPayload = ArtifactViewerSinglePayload | ArtifactViewerContextPayload | ArtifactViewerJwtPayload | ArtifactViewerEventPayload;

const STORAGE_PREFIX = "smart-permission-tickets:artifact:";

export function buildArtifactViewerHref(payload: ArtifactViewerPayload) {
  const key = crypto.randomUUID();
  localStorage.setItem(`${STORAGE_PREFIX}${key}`, JSON.stringify(payload));
  return `/viewer?artifact_key=${encodeURIComponent(key)}`;
}

export function loadArtifactViewerPayload(key: string) {
  const raw = localStorage.getItem(`${STORAGE_PREFIX}${key}`);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as ArtifactViewerPayload;
  } catch {
    return null;
  }
}

export function renderArtifactText(payload: ArtifactViewerPayload) {
  if (payload.kind === "jwt") return payload.jwt;
  if (payload.kind === "event") return JSON.stringify(payload.event, null, 2);
  if (payload.kind === "context") {
    const focus = payload.nodes.find((node) => node.ref === payload.focusRef) ?? payload.nodes[0];
    if (!focus) return "";
    if (typeof focus.content === "string") return focus.content;
    return JSON.stringify(focus.content, null, 2);
  }
  if (typeof payload.content === "string") return payload.content;
  return JSON.stringify(payload.content, null, 2);
}

export function buildJwtArtifactPayload(input: {
  title: string;
  jwt: string;
  subtitle?: string;
  metadata?: ArtifactViewerMetadata[];
  noteText?: string | null;
}) {
  return {
    kind: "jwt" as const,
    title: input.title,
    subtitle: input.subtitle,
    jwt: input.jwt,
    copyText: input.jwt,
    metadata: input.metadata,
    noteText: input.noteText ?? null,
  };
}

export function buildDemoEventArtifactPayload(event: DemoEvent) {
  return {
    kind: "event" as const,
    title: event.label,
    subtitle: `${deriveDemoEventPhase(event)} · #${event.seq}`,
    event,
  };
}

export function buildDemoEventSummary(event: DemoEvent): ArtifactViewerEventSummary {
  const noteText = "Internal audit event generated by the reference server for demo visualization. This summary is not part of the protocol wire format.";
  switch (event.type) {
    case "ticket-created":
      return {
        description: `The issuer signed a permission ticket for ${event.detail.patientName}.`,
        fields: [
          { label: "Patient", value: event.detail.patientName },
          { label: "Scopes", value: event.detail.scopes.join(", ") },
          { label: "Dates", value: event.detail.dateSummary },
          { label: "Sensitive", value: event.detail.sensitiveSummary },
          { label: "Expires", value: event.detail.expirySummary },
          { label: "Binding", value: event.detail.bindingSummary },
        ],
        noteText,
      };
    case "registration-request":
      return {
        description:
          event.detail.outcome === "registered"
            ? `${capitalize(event.detail.authMode)} registration succeeded.`
            : event.detail.outcome === "cancelled"
              ? `${capitalize(event.detail.authMode)} registration was cancelled.`
              : `${capitalize(event.detail.authMode)} registration was rejected.`,
        fields: [
          { label: "Endpoint", value: event.detail.endpoint },
          { label: "Auth mode", value: event.detail.authMode },
          { label: "Outcome", value: event.detail.outcome },
          ...(event.detail.siteName ? [{ label: "Site", value: event.detail.siteName }] : []),
          ...(event.detail.clientId ? [{ label: "Client ID", value: event.detail.clientId }] : []),
          ...(event.detail.registrationMode ? [{ label: "Registration mode", value: event.detail.registrationMode }] : []),
          ...(event.detail.frameworkUri ? [{ label: "Framework", value: event.detail.frameworkUri }] : []),
          ...(event.detail.entityUri ? [{ label: "Entity URI", value: event.detail.entityUri }] : []),
          ...(event.detail.algorithm ? [{ label: "Algorithm", value: event.detail.algorithm }] : []),
          ...(event.detail.error ? [{ label: "Error", value: event.detail.error }] : []),
        ],
        steps: event.detail.steps,
        noteText,
      };
    case "token-exchange":
      return {
        description:
          event.detail.outcome === "issued"
            ? `The token endpoint accepted this ${event.detail.grantType} request and issued an access token.`
            : `The token endpoint rejected this ${event.detail.grantType} request.`,
        fields: [
          { label: "Endpoint", value: event.detail.endpoint },
          { label: "Grant type", value: event.detail.grantType },
          { label: "Mode", value: event.detail.mode },
          { label: "Outcome", value: event.detail.outcome },
          ...(event.detail.siteName ? [{ label: "Site", value: event.detail.siteName }] : []),
          ...(event.detail.scopeSummary ? [{ label: "Issued scope", value: event.detail.scopeSummary }] : []),
          ...(typeof event.detail.authorizedSiteCount === "number" ? [{ label: "Authorized sites", value: String(event.detail.authorizedSiteCount) }] : []),
          ...(event.detail.error ? [{ label: "Error", value: event.detail.error }] : []),
        ],
        steps: event.detail.steps,
        patientMatch: event.detail.patientMatch
          ? event.detail.patientMatch.siteName
            ? `${event.detail.patientMatch.patientName} at ${event.detail.patientMatch.siteName}`
            : `${event.detail.patientMatch.patientName} at ${event.detail.patientMatch.siteCount} sites`
          : null,
        noteText,
      };
    case "udap-discovery":
      return {
        description: "The viewer fetched UDAP discovery metadata from the authorization server.",
        fields: [{ label: "Endpoint", value: event.detail.endpoint }],
        noteText,
      };
    case "sites-discovered":
      return {
        description: "The network resolved record locations for the matched patient.",
        fields: [{ label: "Sites", value: event.detail.sites.map((site) => site.siteName).join(", ") }],
        noteText,
      };
    case "query-result":
      return {
        description: `The site returned ${event.detail.count} ${event.detail.resourceType} resource${event.detail.count === 1 ? "" : "s"}.`,
        fields: [
          { label: "Site", value: event.detail.siteName },
          { label: "Resource type", value: event.detail.resourceType },
          { label: "Count", value: String(event.detail.count) },
          { label: "Query", value: event.detail.queryPath },
        ],
        noteText,
      };
    case "query-failed":
      return {
        description: `The site query for ${event.detail.resourceType} failed.`,
        fields: [
          { label: "Site", value: event.detail.siteName },
          { label: "Resource type", value: event.detail.resourceType },
          { label: "Query", value: event.detail.queryPath },
          { label: "Error", value: event.detail.reason },
        ],
        noteText,
      };
    case "session-complete":
      return {
        description: "The viewer finished assembling the demo session.",
        fields: [
          { label: "Sites", value: String(event.detail.totalSites) },
          { label: "Resources", value: String(event.detail.totalResources) },
          { label: "Queries", value: String(event.detail.queryCount) },
        ],
        noteText,
      };
  }
}

export function decodeJwtArtifact(jwt: string) {
  const [encodedHeader, encodedPayload, signature, ...rest] = jwt.split(".");
  if (!encodedHeader || !encodedPayload || !signature || rest.length) {
    throw new Error("Malformed JWT");
  }
  return {
    header: decodeJwtJson(encodedHeader),
    payload: decodeJwtJson(encodedPayload),
    signature,
    compact: jwt,
  };
}

function decodeJwtJson(segment: string) {
  const normalized = segment.replace(/-/g, "+").replace(/_/g, "/");
  const padding = normalized.length % 4 === 0 ? "" : "=".repeat(4 - (normalized.length % 4));
  return JSON.parse(atob(`${normalized}${padding}`));
}

function capitalize(value: string) {
  return value ? `${value.slice(0, 1).toUpperCase()}${value.slice(1)}` : value;
}
