import {
  PATIENT_DELEGATED_ACCESS_TICKET_TYPE,
  PATIENT_SELF_ACCESS_TICKET_TYPE,
  PAYER_CLAIMS_ADJUDICATION_TICKET_TYPE,
  PermissionTicketTypeValues,
  PROVIDER_CONSULT_TICKET_TYPE,
  PUBLIC_HEALTH_INVESTIGATION_TICKET_TYPE,
  RESEARCH_STUDY_ACCESS_TICKET_TYPE,
  SOCIAL_CARE_REFERRAL_TICKET_TYPE,
} from "../../shared/permission-ticket-schema.ts";

export const SMART_PERMISSION_TICKET_CONFIG_EXTENSION_URL =
  "https://smarthealthit.org/smart-permission-tickets/smart-configuration";

export {
  PATIENT_DELEGATED_ACCESS_TICKET_TYPE,
  PATIENT_SELF_ACCESS_TICKET_TYPE,
  PAYER_CLAIMS_ADJUDICATION_TICKET_TYPE,
  PROVIDER_CONSULT_TICKET_TYPE,
  PUBLIC_HEALTH_INVESTIGATION_TICKET_TYPE,
  RESEARCH_STUDY_ACCESS_TICKET_TYPE,
  SOCIAL_CARE_REFERRAL_TICKET_TYPE,
};

export const PERMISSION_TICKET_SUBJECT_TOKEN_TYPE =
  "https://smarthealthit.org/token-type/permission-ticket";

export const SUPPORTED_PERMISSION_TICKET_TYPES = PermissionTicketTypeValues;
