import { callClaude, encId } from "./lib.ts";

const JSON_REPAIR_PROMPT = `# JSON Repair

You repair malformed JSON generated by another model.

## Task

- Return valid JSON only
- Preserve the original content, ordering, and factual meaning
- Fix syntax only: stray braces, commas, quotes, code fences, or unescaped control characters
- Do not add commentary
- Do not omit objects unless the input is irreparably truncated`;

export interface ProviderMapPatient {
  full_name?: string;
  date_of_birth?: string;
  gender?: string;
  race_ethnicity?: string;
  language?: string;
  marital_status?: string;
  home_city?: string;
  home_state?: string;
  address_summary?: string;
}

export interface ProviderMapClinician {
  name: string;
  role?: string;
  npi?: string | null;
}

export interface ProviderMapLocation {
  name: string;
  city?: string;
  state?: string;
  address_summary?: string;
}

export interface ProviderSiteContract {
  site_slug: string;
  site_name: string;
  npi: string;
  site_type?: string;
  city?: string;
  state: string;
  active_period?: {
    start?: string;
    end?: string | null;
  };
  key_clinicians: ProviderMapClinician[];
  locations: ProviderMapLocation[];
  narrative_summary?: string;
}

export interface ProviderMap {
  patient: ProviderMapPatient;
  sites: ProviderSiteContract[];
}

export interface EncounterRecord {
  encounter_index: number;
  encounter_id: string;
  site_slug: string;
  site_name: string;
  site_npi: string;
  state: string;
  date: string;
  encounter_type: string;
  reason: string;
  clinician_names: string[];
  location?: string;
  header: string;
  body_markdown: string;
}

export interface EncounterTimeline {
  encounters: EncounterRecord[];
}

export interface EncounterInventorySidecar {
  encounter_id: string;
  encounter_index: number;
  site_slug: string;
  encounter: {
    class?: string;
    type?: string;
    reason?: string;
    period_start?: string;
    period_end?: string;
    participants: Array<Record<string, any>>;
    service_provider?: string;
    location?: string;
  };
  observations: {
    vitals: Array<Record<string, any>>;
    labs: Array<Record<string, any>>;
    screening: Array<Record<string, any>>;
  };
  conditions: Array<Record<string, any>>;
  medications: Array<Record<string, any>>;
  procedures: Array<Record<string, any>>;
  immunizations: Array<Record<string, any>>;
  document_references: Array<Record<string, any>>;
  diagnostic_reports: Array<Record<string, any>>;
  allergies: Array<Record<string, any>>;
}

type DiagnosticReportState = "report-with-results" | "summary-only" | "ordered-not-resulted";

export function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function asTrimmedString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function requireString(value: unknown, label: string): string {
  const str = asTrimmedString(value);
  if (!str) throw new Error(`${label} is required`);
  return str;
}

function stringArray(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value
      .map(item => (typeof item === "string" ? item.trim() : ""))
      .filter(Boolean);
  }
  const single = asTrimmedString(value);
  return single ? [single] : [];
}

function objectArray(value: unknown): Array<Record<string, any>> {
  return Array.isArray(value)
    ? value.filter((item): item is Record<string, any> => !!item && typeof item === "object" && !Array.isArray(item))
    : [];
}

function normalizeReportState(value: unknown): DiagnosticReportState | undefined {
  const raw = asTrimmedString(value)?.toLowerCase();
  if (!raw) return undefined;
  if (raw === "report-with-results" || raw === "summary-only" || raw === "ordered-not-resulted") {
    return raw;
  }
  if (raw === "results" || raw === "with-results" || raw === "backed-by-results") return "report-with-results";
  if (raw === "summary" || raw === "normal-summary" || raw === "summary report") return "summary-only";
  if (raw === "ordered" || raw === "pending" || raw === "not-resulted") return "ordered-not-resulted";
  return undefined;
}

function inferObservationNameFromResultText(value: string): string {
  return value
    .replace(/\s+[<>]?\d[\d.,/%-]*(?:\s*[A-Za-z%/()[\].-][A-Za-z0-9%/()[\].-]*)*$/u, "")
    .trim();
}

function normalizeDiagnosticReports(
  value: unknown,
  allObservationNames: Set<string>,
): Array<Record<string, any>> {
  return objectArray(value).map((item, index) => {
    const legacyResults = stringArray(item.results);
    const observationNames = stringArray(item.observation_names)
      .concat(legacyResults.map(inferObservationNameFromResultText))
      .map(name => name.trim())
      .filter(Boolean);
    const uniqueObservationNames = [...new Set(observationNames)];

    const reportState = normalizeReportState(item.report_state ?? item.state)
      ?? (uniqueObservationNames.length > 0 ? "report-with-results" : "summary-only");

    if (reportState === "report-with-results" && uniqueObservationNames.length === 0) {
      throw new Error(`diagnostic_reports[${index}] with report-with-results must include observation_names`);
    }

    if (reportState !== "report-with-results" && uniqueObservationNames.length > 0) {
      throw new Error(`diagnostic_reports[${index}] may only include observation_names when report_state is report-with-results`);
    }

    for (const observationName of uniqueObservationNames) {
      if (!allObservationNames.has(observationName.toLowerCase())) {
        throw new Error(
          `diagnostic_reports[${index}] references observation "${observationName}" that is not present in observations.vitals/labs/screening`,
        );
      }
    }

    const description = asTrimmedString(item.description);
    if (reportState !== "report-with-results" && !description) {
      throw new Error(`diagnostic_reports[${index}] with ${reportState} must include description`);
    }

    return {
      type: asTrimmedString(item.type),
      report_state: reportState,
      ...(uniqueObservationNames.length > 0 ? { observation_names: uniqueObservationNames } : {}),
      ...(description ? { description } : {}),
    };
  });
}

export function extractJsonPayload(text: string): string {
  const trimmed = text.trim();
  if (
    (trimmed.startsWith("{") && trimmed.endsWith("}"))
    || (trimmed.startsWith("[") && trimmed.endsWith("]"))
  ) {
    return trimmed;
  }

  const fenced = text.match(/```json\s*([\s\S]*?)\s*```/i);
  if (fenced) return fenced[1].trim();

  const arrayStart = text.indexOf("[");
  const arrayEnd = text.lastIndexOf("]");
  if (arrayStart >= 0 && arrayEnd > arrayStart) {
    const objectStart = text.indexOf("{");
    if (objectStart >= 0 && objectStart < arrayStart) {
      const objectEnd = text.lastIndexOf("}");
      if (objectEnd > objectStart) return text.slice(objectStart, objectEnd + 1).trim();
    }
    return text.slice(arrayStart, arrayEnd + 1).trim();
  }

  const objectStart = text.indexOf("{");
  const objectEnd = text.lastIndexOf("}");
  if (objectStart >= 0 && objectEnd > objectStart) {
    return text.slice(objectStart, objectEnd + 1).trim();
  }

  return text.trim();
}

function escapeControlCharsInJsonStrings(text: string): string {
  let out = "";
  let inString = false;
  let escaping = false;

  for (const ch of text) {
    if (escaping) {
      out += ch;
      escaping = false;
      continue;
    }

    if (ch === "\\") {
      out += ch;
      escaping = true;
      continue;
    }

    if (ch === "\"") {
      out += ch;
      inString = !inString;
      continue;
    }

    if (inString) {
      if (ch === "\n") {
        out += "\\n";
        continue;
      }
      if (ch === "\r") {
        out += "\\r";
        continue;
      }
      if (ch === "\t") {
        out += "\\t";
        continue;
      }
    }

    out += ch;
  }

  return out;
}

/** Strip whitespace from base64 `data` fields (LLMs sometimes line-wrap them) */
export function normalizeAttachmentData(value: any): any {
  if (Array.isArray(value)) return value.map(normalizeAttachmentData);
  if (!value || typeof value !== "object") return value;
  const copy: Record<string, any> = {};
  for (const [key, child] of Object.entries(value)) {
    if (key === "data" && typeof child === "string") {
      copy[key] = child.replace(/\s+/g, "");
    } else {
      copy[key] = normalizeAttachmentData(child);
    }
  }
  return copy;
}

/** Parse a JSON array of FHIR resources from LLM output, with control char escaping */
export function parseResourceArray(text: string): any[] {
  const payload = extractJsonPayload(text);
  const candidates = [payload, escapeControlCharsInJsonStrings(payload)];
  let lastError: unknown;
  for (const candidate of candidates) {
    try {
      const parsed = JSON.parse(candidate);
      const resources = Array.isArray(parsed) ? parsed : [parsed];
      return resources.map(normalizeAttachmentData);
    } catch (error) {
      lastError = error;
    }
  }
  throw lastError ?? new Error("Failed to parse generated JSON");
}

/** Parse resources with Haiku repair fallback */
export async function parseResourceArrayWithRepair(text: string, repairLabel = "FHIR resources"): Promise<any[]> {
  try {
    return parseResourceArray(text);
  } catch {
    const payload = extractJsonPayload(text);
    const repaired = await callClaude({
      systemPrompt: JSON_REPAIR_PROMPT,
      userMessage: `Repair this malformed ${repairLabel} JSON array and return only valid JSON.\n\n${payload}`,
      outputFileName: "output.json",
    });
    return parseResourceArray(repaired);
  }
}

export async function parseJsonArtifact(text: string, repairLabel = "JSON"): Promise<any> {
  const payload = extractJsonPayload(text);
  const candidates = [payload, escapeControlCharsInJsonStrings(payload)];

  let lastError: unknown;
  for (const candidate of candidates) {
    try {
      return JSON.parse(candidate);
    } catch (error) {
      lastError = error;
    }
  }

  const repaired = await callClaude({
    systemPrompt: JSON_REPAIR_PROMPT,
    userMessage: `Repair this malformed ${repairLabel} and return only valid JSON.\n\n${payload}`,
    outputFileName: "output.json",
  });

  return JSON.parse(escapeControlCharsInJsonStrings(extractJsonPayload(repaired)));
}

export async function generateJsonArtifact(opts: {
  systemPrompt: string;
  userMessage: string;
  repairLabel?: string;
}): Promise<any> {
  const result = await callClaude({
    systemPrompt: opts.systemPrompt,
    userMessage: opts.userMessage,
    outputFileName: "output.json",
  });
  return parseJsonArtifact(result, opts.repairLabel);
}

export function normalizeProviderMap(raw: any): ProviderMap {
  const patientSource = raw?.patient && typeof raw.patient === "object" ? raw.patient : {};
  const patient: ProviderMapPatient = {
    full_name: asTrimmedString(patientSource.full_name),
    date_of_birth: asTrimmedString(patientSource.date_of_birth),
    gender: asTrimmedString(patientSource.gender),
    race_ethnicity: asTrimmedString(patientSource.race_ethnicity),
    language: asTrimmedString(patientSource.language),
    marital_status: asTrimmedString(patientSource.marital_status),
    home_city: asTrimmedString(patientSource.home_city),
    home_state: asTrimmedString(patientSource.home_state)?.toUpperCase(),
    address_summary: asTrimmedString(patientSource.address_summary),
  };

  const sitesSource = objectArray(raw?.sites);
  if (sitesSource.length === 0) throw new Error("provider-map.json must contain a non-empty sites array");

  const seenSlugs = new Set<string>();
  const sites: ProviderSiteContract[] = sitesSource.map((site, index) => {
    const siteName = requireString(site.site_name ?? site.name, `sites[${index}].site_name`);
    const siteSlug = slugify(requireString(site.site_slug ?? siteName, `sites[${index}].site_slug`));
    const npi = requireString(site.npi, `sites[${index}].npi`);
    const state = requireString(site.state, `sites[${index}].state`).toUpperCase();

    if (!/^\d{10}$/.test(npi)) {
      throw new Error(`sites[${index}].npi must be a 10-digit string`);
    }
    if (seenSlugs.has(siteSlug)) {
      throw new Error(`duplicate site_slug: ${siteSlug}`);
    }
    seenSlugs.add(siteSlug);

    const clinicians = objectArray(site.key_clinicians ?? site.clinicians).map((clinician, clinicianIndex) => ({
      name: requireString(clinician.name, `sites[${index}].key_clinicians[${clinicianIndex}].name`),
      role: asTrimmedString(clinician.role),
      npi: asTrimmedString(clinician.npi) ?? null,
    }));

    const locations = objectArray(site.locations).map((location, locationIndex) => ({
      name: requireString(location.name, `sites[${index}].locations[${locationIndex}].name`),
      city: asTrimmedString(location.city),
      state: asTrimmedString(location.state)?.toUpperCase(),
      address_summary: asTrimmedString(location.address_summary),
    }));

    const activePeriod = site.active_period && typeof site.active_period === "object"
      ? {
          start: asTrimmedString(site.active_period.start),
          end: asTrimmedString(site.active_period.end) ?? null,
        }
      : undefined;

    return {
      site_slug: siteSlug,
      site_name: siteName,
      npi,
      state,
      city: asTrimmedString(site.city),
      site_type: asTrimmedString(site.site_type ?? site.type),
      active_period: activePeriod,
      key_clinicians: clinicians,
      locations,
      narrative_summary: asTrimmedString(site.narrative_summary),
    };
  });

  return { patient, sites };
}

export async function loadProviderMap(filePath: string): Promise<ProviderMap> {
  return normalizeProviderMap(JSON.parse(await Bun.file(filePath).text()));
}

function siteMap(providerMap: ProviderMap): Map<string, ProviderSiteContract> {
  return new Map(providerMap.sites.map(site => [site.site_slug, site]));
}

function buildEncounterHeader(record: {
  date: string;
  encounter_type: string;
  reason: string;
}): string {
  return `${record.date} — ${record.encounter_type} — ${record.reason}`;
}

export function normalizeEncounterTimeline(raw: any, providerMap: ProviderMap): EncounterTimeline {
  const source = Array.isArray(raw?.encounters) ? raw.encounters : Array.isArray(raw) ? raw : [];
  if (source.length === 0) throw new Error("encounters.json must contain a non-empty encounters array");

  const sitesBySlug = siteMap(providerMap);
  const seenIds = new Set<string>();
  const seenIndexes = new Set<number>();

  const encounters: EncounterRecord[] = source.map((encounter: any, fallbackIndex: number): EncounterRecord => {
    if (!encounter || typeof encounter !== "object" || Array.isArray(encounter)) {
      throw new Error(`encounters[${fallbackIndex}] must be an object`);
    }

    const encounterIndex = Number.isInteger(encounter.encounter_index)
      ? encounter.encounter_index
      : fallbackIndex;
    const encounterId = requireString(encounter.encounter_id ?? `enc-${encId(encounterIndex)}`, `encounters[${fallbackIndex}].encounter_id`);
    const date = requireString(encounter.date, `encounters[${fallbackIndex}].date`);

    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      throw new Error(`encounters[${fallbackIndex}].date must be YYYY-MM-DD`);
    }
    if (seenIndexes.has(encounterIndex)) {
      throw new Error(`duplicate encounter_index: ${encounterIndex}`);
    }
    if (seenIds.has(encounterId)) {
      throw new Error(`duplicate encounter_id: ${encounterId}`);
    }
    seenIndexes.add(encounterIndex);
    seenIds.add(encounterId);

    const siteSlug = slugify(requireString(
      encounter.site_slug ?? encounter.site_name,
      `encounters[${fallbackIndex}].site_slug`,
    ));
    const site = sitesBySlug.get(siteSlug);
    if (!site) throw new Error(`encounters[${fallbackIndex}] references unknown site_slug: ${siteSlug}`);

    const bodyMarkdown = requireString(
      encounter.body_markdown ?? encounter.body ?? encounter.markdown,
      `encounters[${fallbackIndex}].body_markdown`,
    );
    if (/(^|\n)##\s+Site\b/.test(bodyMarkdown) || /(^|\n)###\s+\d{4}-\d{2}-\d{2}\b/.test(bodyMarkdown)) {
      throw new Error(`encounters[${fallbackIndex}].body_markdown still contains site/encounter headers`);
    }

    const encounterType = requireString(
      encounter.encounter_type ?? encounter.type,
      `encounters[${fallbackIndex}].encounter_type`,
    );
    const reason = requireString(encounter.reason, `encounters[${fallbackIndex}].reason`);
    const clinicianNames = stringArray(encounter.clinician_names ?? encounter.clinicians ?? encounter.clinician_name);

    return {
      encounter_index: encounterIndex,
      encounter_id: encounterId,
      site_slug: site.site_slug,
      site_name: site.site_name,
      site_npi: site.npi,
      state: site.state,
      date,
      encounter_type: encounterType,
      reason,
      clinician_names: clinicianNames,
      location: asTrimmedString(encounter.location),
      header: asTrimmedString(encounter.header) ?? buildEncounterHeader({ date, encounter_type: encounterType, reason }),
      body_markdown: bodyMarkdown,
    };
  });

  encounters.sort((a: EncounterRecord, b: EncounterRecord) => a.encounter_index - b.encounter_index);
  encounters.forEach((encounter: EncounterRecord, index: number) => {
    if (encounter.encounter_index !== index) {
      throw new Error(`encounters.json must use contiguous encounter_index values starting at 0; found ${encounter.encounter_index} at position ${index}`);
    }
    if (encounter.encounter_id !== `enc-${encId(index)}`) {
      throw new Error(`encounter_id must match encounter_index; expected enc-${encId(index)} but found ${encounter.encounter_id}`);
    }
  });

  return { encounters };
}

export async function loadEncounterTimeline(filePath: string, providerMap: ProviderMap): Promise<EncounterTimeline> {
  return normalizeEncounterTimeline(JSON.parse(await Bun.file(filePath).text()), providerMap);
}

export function groupEncountersBySite(timeline: EncounterTimeline): Map<string, EncounterRecord[]> {
  const grouped = new Map<string, EncounterRecord[]>();
  for (const encounter of timeline.encounters) {
    if (!grouped.has(encounter.site_slug)) grouped.set(encounter.site_slug, []);
    grouped.get(encounter.site_slug)!.push(encounter);
  }
  return grouped;
}

export function normalizeInventorySidecar(raw: any, encounter: EncounterRecord): EncounterInventorySidecar {
  const payload = raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {};
  const observations = payload.observations && typeof payload.observations === "object" && !Array.isArray(payload.observations)
    ? payload.observations
    : {};
  const encounterBlock = payload.encounter && typeof payload.encounter === "object" && !Array.isArray(payload.encounter)
    ? payload.encounter
    : {};

  const vitals = objectArray(observations.vitals);
  const labs = objectArray(observations.labs);
  const screening = objectArray(observations.screening);
  const allObservationNames = new Set(
    [...vitals, ...labs, ...screening]
      .map(item => asTrimmedString(item.name)?.toLowerCase())
      .filter((name): name is string => Boolean(name)),
  );

  return {
    encounter_id: encounter.encounter_id,
    encounter_index: encounter.encounter_index,
    site_slug: encounter.site_slug,
    encounter: {
      class: asTrimmedString(encounterBlock.class),
      type: asTrimmedString(encounterBlock.type),
      reason: asTrimmedString(encounterBlock.reason),
      period_start: asTrimmedString(encounterBlock.period_start),
      period_end: asTrimmedString(encounterBlock.period_end),
      participants: objectArray(encounterBlock.participants),
      service_provider: asTrimmedString(encounterBlock.service_provider),
      location: asTrimmedString(encounterBlock.location),
    },
    observations: {
      vitals,
      labs,
      screening,
    },
    conditions: objectArray(payload.conditions),
    medications: objectArray(payload.medications),
    procedures: objectArray(payload.procedures),
    immunizations: objectArray(payload.immunizations),
    document_references: objectArray(payload.document_references ?? payload.documents),
    diagnostic_reports: normalizeDiagnosticReports(payload.diagnostic_reports, allObservationNames),
    allergies: objectArray(payload.allergies),
  };
}

export async function loadInventorySidecar(filePath: string, encounter: EncounterRecord): Promise<EncounterInventorySidecar> {
  return normalizeInventorySidecar(JSON.parse(await Bun.file(filePath).text()), encounter);
}

export function findSiteContract(providerMap: ProviderMap, siteSlug: string): ProviderSiteContract {
  const site = siteMap(providerMap).get(siteSlug);
  if (!site) throw new Error(`Unknown site_slug: ${siteSlug}`);
  return site;
}
